services:
  # Application service
  app:
    build: .
    depends_on:
      - db

  # MySQL database service
  db:
    build: ./db  # Update this to point to the world-db directory
    command: --default-authentication-plugin=mysql_native_password
    restart: always

