name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  UnitTests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Run Unit Tests
        run: mvn test

  IntegrationTests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Start Docker
        run: docker-compose up -d
      - name: Run Integration Tests
        run: mvn -Dtest=com.napier.sem.AppIntegrationTest test
      - name: Stop Docker
        run: docker-compose down

  CodeCoverage:
    name: Upload Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Run Tests and Coverage
        run: mvn test
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./target/site/jacoco